"""followers

Revision ID: 562a3caf8573
Revises: 16e016264ca0
Create Date: 2020-04-03 15:36:42.523121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '562a3caf8573'
down_revision = '16e016264ca0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
